my_cidr = "X.X.X.X/32"
db_name = "fortunes"
image   = "account.endpoint/repo:tag"
cw_image = "account.endpoint/repo:tag"
aws_secrets_loc = "path/to/secret" // Within Secrets Manager. i.e. "dev/db_creds/webserver_k8s"
