my_cidr = "X.X.X.X/32"
db_name = "fortunes"
aws_config_file = "/path/to/.aws/config"
aws_cred_file = "/path/to/.aws/credentials"
aws_profile = "default"
aws_secrets_loc = "path/to/secret" // Within Secrets Manager. i.e. "dev/db_creds/webserver_k8s"